### PR TITLE
Adding HTTP Proxy

### LINKED ISSUE #2014: Is there a way to set proxy settings ?
Hi !

Trying to use gitbeaker behind a corporate proxy, is it possible ?

### Steps to reproduce

- Behind a corporate proxy
- Any request to Gitlab 
```
const api = new Gitlab({
    host: 'https://gitlab.com',
    token: 'my-token',
});
let projects = await api.Groups.projects("anyid", {maxPages: 2, perPage: 40 });
```

### Actual behavior

As no proxy has been defined...

```
RequestError: getaddrinfo ENOTFOUND gitlab.com
```

Thanks

### PR DESCRIPTION
**Pull request by TBG-FR**
This PR aims to add the possibility to set a HTTP proxy, using environment variables. It answers to the following issue (and implemented a solution using the advice given here) : [Is there a way to set proxy settings ?](https://github.com/jdalrymple/gitbeaker/issues/2014)

So from now, you can set `GLOBAL_AGENT_HTTPS_PROXY` if you have proxy needs, and it will work 👌 

## Pull Request Process

- [X] Ensure any install or build dependencies are removed before the end of the layer when doing a build.
- [X] Update the README.md with details of changes to the interface, this includes new environment variables, exposed ports, useful file locations and container parameters.
- [ ] Increase the version numbers in any examples files and the README.md to the new version that this Pull Request would represent. The versioning scheme we use is [SemVer](http://semver.org/).

## Additionnal notes

The solution implemented uses 'global-agent`, but it looks like it didn't need a `npm install global-agent` to add it to the `package.json`, I suppose it's included in another lib used by the package (maybe `got` ?). If you want me to add it "in case of", I can do that !

Thanks in advance for checking that PR 😄 

closes #2014

### CODE REVIEW

**Comment by jdalrymple** [comment]
Amazing, ill give it a look to double check the functionality and its limits!

**Comment by TBG-FR** [comment]
This needs further work. I finally stopped using `gitbeaker` and did my Gitlab API requests using "raw" node/ts for now.

When adding a proxy, `gitbeaker`'s request (=> `got` requests) are facing a `HTTP 403 Forbidden` error which I couldn't solve. It works using `fetch`/`got` or even `cURL`, so I believe the issue lies in gitbeaker's code 👀 **TODO**

**Comment by twinkle77** [comment]
image

Global-agent may affects global code ？
What if I just want Got use a proxy
@TBG-FR

**Comment by jdalrymple** [comment]
Recently switched things to native fetch, is this functionality supported through the fetch api in any fashion?

**Pull request closed without merging**
