### PR TITLE
Reach > 90% coverage and add Integration Testing

### LINKED ISSUE #309: Create a multi-environment testing script
**Description**
There are three compiled versions of this library, one for the browser, one for commonjs and one as a es module. However, the testing procedures only run on the src and supported nodejs versions. This has led to some problems in the past where the released binaries have errors that were not captured during the testing procedure.

**Proposal**
Overhaul the testing procedure to additionally run the tests on the compiled binaries for each environment.

### LINKED ISSUE #686: Error on constructor
**Description**
I have an application in Vue and when trying to run the contructor, it gives the following error.

image

```
_gitbeaker_browser__WEBPACK_IMPORTED_MODULE_6__.Gitlab is not a constructor
    at new GitLab (gitlab.js:7)
    at _callee5$ (AfterLogin.vue:369)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:274)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at asyncGeneratorStep (asyncToGenerator.js:3)
    at _next (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at VueComponent.getUser (AfterLogin.vue:361)
    at VueComponent.getInfo (AfterLogin.vue:304)
    at VueComponent.mounted (AfterLogin.vue:193)
    at invokeWithErrorHandling (vue.runtime.esm.js:1854)
    at callHook (vue.runtime.esm.js:4219)
    at Object.insert (vue.runtime.esm.js:3139)
    at invokeInsertHook (vue.runtime.esm.js:6346)
    at Vue.patch [as __patch__] (vue.runtime.esm.js:6565)
    at Vue._update (vue.runtime.esm.js:3945)
    at Vue.updateComponent (vue.runtime.esm.js:4066)
    at Watcher.get (vue.runtime.esm.js:4479)
    at new Watcher (vue.runtime.esm.js:4468)
    at mountComponent (vue.runtime.esm.js:4073)
    at Vue.push../node_modules/vue/dist/vue.runtime.esm.js.Vue.$mount (vue.runtime.esm.js:8415)
    at Module../src/main.js (main.js:53)
    at __webpack_require__ (bootstrap:784)
    at fn (bootstrap:150)
    at Object.1 (Settings.vue?66a4:1)
    at __webpack_require__ (bootstrap:784)
    at checkDeferredModules (bootstrap:45)
    at bootstrap:860
    at bootstrap:860
```

**Steps to reproduce**
## Dependencies
node: v10
```json
  "vue": "^2.6.11",
  "@gitbeaker/browser": "^17.0.1",
```
## Code
```vue
import { Gitlab } from "@gitbeaker/browser";

const token = "<token>";
try {
  const api = new Gitlab({
    token
  });
} catch(err) {
  console.error(err);
}
```

### LINKED ISSUE #698: 'Gitlab' is not exported from '@gitbeaker/node'.
**Description**

I am working on a react dashboard trying to import the git client from @gitbeaker/node as follows:

`import { Gitlab } from '@gitbeaker/node';`

I get the following warning in the editor:

```
module "d:/_dev/pcte/vdk-dashboard/node_modules/@gitbeaker/node/dist/index"
Could not find a declaration file for module '@gitbeaker/node'. 'd:/_dev/pcte/vdk-dashboard/node_modules/@gitbeaker/node/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/gitbeaker__node` if it exists or add a new declaration (.d.ts) file containing `declare module '@gitbeaker/node';`ts(7016)
```
I saw this with v18.0.0 and the previous version.
My version of node is 13.12.0.
I tried the workaround for this issue #304, but that didn't work for me.

**Steps to reproduce**

When I run the service (npm start) I get the following output:
```
./src/services/gitlabClient.js
Attempted import error: 'Gitlab' is not exported from '@gitbeaker/node'.
```

Here is my package.json:
```
{
  "name": "react-admin-dashboard",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@gitbeaker/node": "^18.0.0",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "aphrodite": "^2.4.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "react-svg-line-chart": "^2.0.2",
    "simple-flexbox": "^2.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

**Expected behaviour**
I expect there to be a Gitlab class exported from @gitbeaker/node. I have also tried Projects and ProjectsBundle with no luck.

**Actual behaviour**
./src/services/gitlabClient.js
Attempted import error: 'Gitlab' is not exported from '@gitbeaker/node'.

**Possible fixes**
I am pretty sure it is me and not you, but maybe this could help your documentation.

### PR DESCRIPTION
**Pull request by jdalrymple**
- Added many many more unit tests to increase coverage to 90% +
- Removed the upsert functionality of PushRules to maintain documented API parity

fixes #686 
fixes #698
fixes #309

### CODE REVIEW

**Comment by jdalrymple** [comment]
> LGTM!

The openpgp tests have been giving me trouble, and we need to verify the typing is correct for the exports.

**Comment by jdalrymple** [comment]
Looks like many parallel calls to the Gitlab instance is resulting in Error 502 Bad Gateway errors. Maybe i have to run these in band?

**Comment by jdalrymple** [comment]
Hmm, how can i change the organization of the tests. Right now when i tests the services in the gitbeaker-node package, none of the files from gitbeaker-core are registered as being covered. I guess since its an imported library. If i moved the tests to gitbeaker-core i would have to defined a requester for the tests, plastically recreating gitbeaker-node just for tests. :/ Ideas?

**Comment by jetersen** [comment]
@jdalrymple I would again advice too use the docker healthy status instead of waiting.

We been using it very successfully over at https://github.com/nmklotas/GitLabApiClient and never had issue with gitlab not being ready.

**Comment by jdalrymple** [comment]
Ill look into switching it up! @jetersen Any thoughts on the test locations?

**Comment by jetersen** [comment]
There must be a way in jest to register internal library especially as jest itself is a mono repo. https://github.com/facebook/jest/tree/master/packages

https://github.com/facebook/jest/issues/3112#issuecomment-398581705

**Comment by jetersen** [comment]
https://github.com/facebook/jest/issues/2418 might be what your looking for.

**Comment by jdalrymple** [comment]
At 84% so far! only 6% more to go :raised_hands:

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`22.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/22.0.0) :rocket:

**Pull request merged**
