### PR TITLE
Handling nesting of not query parameter

### LINKED ISSUE #1158: Getting Issues with "not" search attributes
**Description**
I searched a lot, but I couldn't find any help on my problem:

I try to get issues, that do NOT have special labels. I tried something like this:

```
const p1 = gitlab.Issues.all({
         groupId: GROUP_ID,
         state: "opened",
         scope: "all",
         not: {
            labels: [
               "prio::Low"
            ]
         },
         order_by: "created_at",
         sort: "asc"
      }).then((issuesJSON: any) => {
         const issues = Issue.fromJSONAsArray(issuesJSON);
         prioNeededIssues.push(...issues);
      });
```
I think that this should match the Gitlab API description:
image

But I always got a `404` error, because of following URL that was sent to my Gitlab instance:
```
https://gitlab.company.net/api/v4/groups/2/issues?not=%5Bobject+Object%5D&order_by=created_at&scope=all&sort=asc&state=opened
```

Is this a BUG or did I something wrong?

### PR DESCRIPTION
**Pull request by jdalrymple**
fixes #1158 

<details>
  <summary>📦 Published PR as canary version: <code>24.0.3-canary.1223.201108695.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @gitbeaker/browser@24.0.3-canary.1223.201108695.0
  npm install @gitbeaker/cli@24.0.3-canary.1223.201108695.0
  npm install @gitbeaker/core@24.0.3-canary.1223.201108695.0
  npm install @gitbeaker/node@24.0.3-canary.1223.201108695.0
  npm install @gitbeaker/requester-utils@24.0.3-canary.1223.201108695.0
  # or 
  yarn add @gitbeaker/browser@24.0.3-canary.1223.201108695.0
  yarn add @gitbeaker/cli@24.0.3-canary.1223.201108695.0
  yarn add @gitbeaker/core@24.0.3-canary.1223.201108695.0
  yarn add @gitbeaker/node@24.0.3-canary.1223.201108695.0
  yarn add @gitbeaker/requester-utils@24.0.3-canary.1223.201108695.0
  ```
</details>

### CODE REVIEW

**Comment by jdalrymple** [comment]
@circlesmiler give the canary a look!

**Comment by circlesmiler** [comment]
> @circlesmiler give the canary a look!

Thanks a lot. 👍

**Comment by jdalrymple** [comment]
@circlesmiler Did it work as you expected it to?

**Comment by circlesmiler** [comment]
> @circlesmiler Did it work as you expected it to?

As I wrote in another comment: I‘m not working on the project anymore, because I left the company. Sorry.

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`24.2.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/24.2.0) :rocket:

**Pull request merged**
