### PR TITLE
fix: resourceDiscussions params

### PR DESCRIPTION
**Pull request by jiadi0801**
discussionId can be a hash value.
give a string(body) to options?: BaseRequestOptions is not allowed.

### CODE REVIEW

**Comment by jdalrymple** [comment]
Good catch! Not sure how i missed that one. What I had there for the edit method didnt make any sense lol. LGTM

**Comment by casz** [comment]
link to see current commit author: https://github.com/jdalrymple/gitbeaker/commit/c27d086ffb133d10a0e8b426f1428a02299d0c75.patch

@jiadi0801 
You might want to set up an email alias on your GitHub account 🥇
https://help.github.com/articles/adding-an-email-address-to-your-github-account/

Or look into fixing your git user.email config 😅  
https://help.github.com/articles/setting-your-commit-email-address-in-git
then you would need to amend your commits: https://stackoverflow.com/a/3042512
after changing author

to get proper credit for your commits 🏆

**Comment by jdalrymple** [comment]
Oops! I reverted the merge so you have time to fix the author :)

**Comment by jdalrymple** [comment]
Just reopen a new PR when you get around to fixing up your commit author email :D Sorry for the hassle lol :man_facepalming:

**Comment by JounQin** [comment]
@jdalrymple 

The `discussionId` is still `number` at https://github.com/jdalrymple/gitbeaker/blob/master/packages/core/src/resources/MergeRequestDiscussions.ts#L15, is it expected?

**Pull request merged**
