### PR TITLE
fix: Adding better handling for form type arguments.

### PR DESCRIPTION
**Pull request by jdalrymple**
This should be able to account for any form arguments passed to the requestHelper

BREAKING CHANGE: Trigger.pipeline now has a defined variables property to house all the pipeline variables to be set. Before these variables were set on the root object, but this made it difficult to parse any future options that may be added to this function.

fixes: #568

### CODE REVIEW

**Comment by jdalrymple** [comment]
Ill handle this once #533 has been released! Want to avoid more merge conflicts.

**Comment by gabber235** [comment]
When can we expect this to be merged?

**Comment by jdalrymple** [comment]
Sorry for the delay, im looking to get this moving this week!

**Comment by jdalrymple** [comment]
Rebased. Just waiting for the tests to run

**Pull request merged**
