### PR TITLE
Add ability to request merged_yaml from the Gitlab Lint API

### PR DESCRIPTION
**Pull request by MartinHowarth**
Fix for issue https://github.com/jdalrymple/gitbeaker/issues/2161

Haven't figured out how to test this yet, any advice on whether it's worth making a UT for this would be useful. Need to work out how to use a branch package to test this live as well - will get to that in a week or two most likely.

### CODE REVIEW

**Comment by jdalrymple** [comment]
Looks good to me! 

Hmm to test this, since it depends on what Gitlab actually supports, you could write an integration test which calls this function and check that the returned object includes that new key. An example would be like this https://github.com/jdalrymple/gitbeaker/blob/master/packages/node/test/integration/resources/Projects.ts#L14

Does that make sense?

**Comment by MartinHowarth** [comment]
Thank you for your patience.

Have added an integration test for this - hopefully that just works, otherwise I'll try to work out how to run the tests locally to fix it.

**Comment by jdalrymple** [comment]
Looks good! Ill run it through the pipeline to see how those tests run

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`34.5.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/34.5.0) :rocket:

**Comment by MartinHowarth** [comment]
Thanks so much for finishing this!

**Pull request merged**
