### PR TITLE
Fixing protect request format

### PR DESCRIPTION
**Pull request by jdalrymple**
fixes: #2069

### CODE REVIEW

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`34.4.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/34.4.0) :rocket:

**Comment by jdalrymple** [comment]
Query just adds those properties as a query param since normally post requests only send a body.

Looking at this example

```
curl --request POST --header "PRIVATE-TOKEN: <your_access_token>" "https://gitlab.example.com/api/v4/projects/5/protected_branches?name=*-stable&push_access_level=30&merge_access_level=30&unprotect_access_level=40"
```

The props are sent as query params, so that piece of code should work. Ill double check it though

**Comment by GMZwinge** [comment]
Got it. The problem may not necessarily be due to this specific pull request, but we see the problem below with `34.4.0` and we don't see it with the previous `34.2.0`.

With this set of options:
```
{
  allowed_to_push: [
    {
      access_level: 0,
    },
    {
      user_id: <aPushUserId>,
    },
  ],
  allowed_to_merge: [
    {
      access_level: 0,
    },
    {
      user_id: <aMergeUserId>,
    },
  ],
  allow_force_push: false,
  code_owner_approval_required: false,
}
```
The GitLab UI shows the protect branch with the above user checked, but no role checked when it should have the role "No one" checked.

**Comment by GMZwinge** [comment]
Could https://github.com/jdalrymple/gitbeaker/pull/2142 be the reason?

**Comment by jdalrymple** [comment]
Maybe! Ill test it out

**Pull request merged**
