### PR TITLE
Allow MR discussions to be resolved

### PR DESCRIPTION
**Pull request by sandercox**
While at the same time fixing the fact that discussion ids issued from my gitlab instance are hex-strings and not just 'numbers' as stated in their documentation.

Filed an issue with gitlab too for that: https://gitlab.com/gitlab-org/gitlab/-/issues/358951

### CODE REVIEW

**Comment by jdalrymple** [comment]
Just to avoid doubling the work, ill pull these changes into the new release branch. Ill probably have to cherry pick the commits, but they will be included!

**Comment by sandercox** [comment]
> 

This was a two part fix, number -> string

but also added a method to resolve a merge request discussion. Either this was already in your branch but I didn't see that in your commit. Just to be sure that gets merged too!

**Comment by jdalrymple** [comment]
> > 
> 
> This was a two part fix, number -> string
> 
> but also added a method to resolve a merge request discussion. Either this was already in your branch but I didn't see that in your commit. Just to be sure that gets merged too!

I already had it in the branch haha, just slow on the release. Testing is taking ages

**Comment by sandercox** [comment]
@jdalrymple any timeframe on release... not being a js/ts developer by profession gives me a super hard time trying to build something that depends on my changes so anxiously awaiting a release ;-)

**Comment by jdalrymple** [comment]
@sandercox Sorry for the delay, just have alot going on. Currently dont have a fixed time for the release unfortunately :(

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`35.8.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/35.8.0) :rocket:

**Comment by jdalrymple** [comment]
:rocket: Issue was released in [`37.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/37.0.0) :rocket:

**Pull request merged**
