### PR TITLE
Adding skipci type for rebase

### LINKED ISSUE #3548: Rebase - SKIP_CI
**Description**

It would appear that there is a flag on rebase `skip_ci` which doesn't appear to be in the gitbeaker API

https://docs.gitlab.com/ee/api/merge_requests.html#rebase-a-merge-request

**Proposal**

Would be a nice option to have to ensure a pipeline doesn't get triggered.

### PR DESCRIPTION
**Pull request by jdalrymple**
fixes #3548

### CODE REVIEW

**Comment by jdalrymple** [comment]
Yea looks like there is an error there, ill have to dig into it later and follow up.  I think the gitlab instance config is hitting a problem

**Comment by kingmesal** [comment]
Any luck with the server spin up "magically" fixing itself?

**Comment by jdalrymple** [comment]
hahah unfortunately not that I can see. Its so random that this only started happening. Ill try it again and see if it persists.

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`40.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/40.0.0) :rocket:

**Comment by jdalrymple** [comment]
Surprise haha, i guess the issue has been resolved on the CI side!

**Pull request merged**
