### PR TITLE
Fix - export Webhook Interfaces

### PR DESCRIPTION
**Pull request by elaine-mattos**
Hi!

thanks for the awesome SDK and the newly added Webhook Interfaces!
However, I missed the export statement in your index.ts when trying to import them to my project, so here's the PR that does that! :)

### CODE REVIEW

**Comment by jdalrymple** [comment]
Oh wow. Fail haha thanks!

**Comment by elaine-mattos** [comment]
Please let me know if there's anything I can do to get a green pipeline :)

**Comment by jdalrymple** [comment]
It looks good. It's a pipeline in efficiency. As of right now I don't automatically run the e2e tests since they are resource intensive. The problem is the manual jobs that aren't run label the pipeline as "failed" until they are run -_-. I haven't thought of a good work around haha

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`39.33.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/39.33.0) :rocket:

**Pull request merged**
