### PR TITLE
fix(docs): Change `npm` to `yarn` for development

### PR DESCRIPTION
**Pull request by kiprasmel**
almost fixes https://github.com/jdalrymple/gitbeaker/issues/1105

The remaining error:

```console
$ y build
yarn run v1.22.4
$ lerna run build
lerna notice cli v3.22.1
lerna info Executing command in 5 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@gitbeaker/requester-utils'
lerna ERR! yarn run build stdout:
$ tsc && rollup -c
../../node_modules/@types/jest-environment-puppeteer/index.d.ts:89:11 - error TS2649: Cannot augment module 'browser' with value exports because it resolves to a non-module entity.

89     const browser: Browser;
             ~~~~~~~


Found 1 error.

info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@gitbeaker/requester-utils'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  9.67s user 0.61s system 155% cpu 6.624 total
```

I was able to fix it by removing the line 89 (exactly where the error was coming from), but I'm not sure if this is the correct way to go about things, and this fix isn't even tracked in git.

### CODE REVIEW

**Comment by max-wittig** [comment]
`yarn build` works for me just fine.

**Review by max-wittig — APPROVED** [review]

**Comment by jdalrymple** [comment]
Works for me as well, not sure where that error is coming from :/

**Comment by max-wittig** [comment]
I think we can merge this.

**Comment by jdalrymple** [comment]
> I think we can merge this.

I agree, it just wont get auto pushed up until #1112 is sorted :cry:

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`23.6.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/23.6.0) :rocket:

**Pull request merged**
