### PR TITLE
:up: create todos for issues

### PR DESCRIPTION
**Pull request by s-kazuki**
ref https://github.com/jdalrymple/gitbeaker/issues/924

### CODE REVIEW

**Comment by jdalrymple** [comment]
Not sure this structure is the best. Currently the docs have the functionality explained in each of the specific resources (issue and merge requests) but i feel like moving the createTodo function there could be misleading when you know there is a Todo API.

Having the separate functions, although clear, can be a bit misleading which the term "create[Issue/MergeRequest]" since its not creating either of those, but rather a Todo. 

Another idea would maybe be modifying current create function

```
create(projectId, resourceId, { resourceName: 'mergerequest', ...options })
```

Though its a bit more complex, it maintains the understanding that a todo will be created, ensures that the resourceId parameter is still required, and keeps the same default functionality that is creation on mergerequests. Internally we could change the url it points to depending on the resourceName parameter?

Thoughts?

**Comment by s-kazuki** [comment]
@jdalrymple sounds good.
how about my additional commit??

**Comment by jdalrymple** [comment]
LGTM, ill merge it up this weekend

**Comment by jdalrymple** [comment]
:rocket: PR was released in [`23.0.0`](https://github.com/jdalrymple/gitbeaker/releases/tag/23.0.0) :rocket:

**Pull request merged**
